package constant

type ERROR_CODE string

var (
    ERR_REQUEST_INVALID         ERROR_CODE = "ERR_REQUEST_INVALID"
    ERR_REQUEST_NOTFOUND        ERROR_CODE = "ERR_REQUEST_NOTFOUND"
    ERR_UNAUTHORIZED             ERROR_CODE = "ERR_UNAUTHORIZED"
    ERR_INTERNAL_SERVER_ERROR    ERROR_CODE = "ERR_INTERNAL_SERVER_ERROR"
    ERR_DB_CONNECTION_ERROR      ERROR_CODE = "ERR_DB_CONNECTION_ERROR"
)

var MAP_ERROR_CODE = map[ERROR_CODE]string{
	ERR_UNAUTHORIZED:  "unauthorized",
}